  sudo: required
  language: generic
  services:
    - docker

  before_install:
    - docker build -t docker007guru/docker-react -f Dockerfile.dev .

  script:
    - docker run docker007guru/docker-react npm run test  -- --coverage 
